### ISSUE TITLE
Hide and show certain surfaces 

### ISSUE THREAD

**Issue by cynde** [arindas/papaya-react#1]
Hi!
If I have for example an array with 3 urls for params['surfaces'], can I hide and show each url without reloading the viewer? Because window.papaya.Container.resetViewer(0, params); will reload the viewer and it takes a long time for the loading

**Comment by arindas** [comment]
I think the API described here could be useful:

https://github.com/rii-mango/Papaya/wiki/API#api-methods

That said, how would you achieve this without react, using a fixed set of images? Have you already solved that?

**Comment by cynde** [comment]
@arindas Thank you for replying.
I already checked that methods. I need something like `papaya.Container.hideImage(index, imageIndex)` but for surface. Do you know it?

**Comment by cynde** [comment]
Already found the solution
