### ISSUE TITLE
Interactive Adjustment of Label Overlay in NIfTI Viewer

### ISSUE THREAD

**Issue by mohamed-ladjal** [arindas/papaya-react#2]
I am looking to implement a feature in the NIfTI viewer, where users can interactively adjust the label overlay on top of the image using the mouse. The goal is to enable manual refinement of the overlay's position for better accuracy. Currently, the viewer displays both the NIfTI image and label overlay, and I seek assistance in implementing the mouse-driven adjustment functionality for the overlay.

**Comment by arindas** [comment]
I think this issue is more suited to the main repository on https://github.com/rii-mango/Papaya
